# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-18 05:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bottle_Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('bottle_units', models.CharField(max_length=70)),
                ('cement_units', models.CharField(max_length=20)),
                ('fill_units', models.CharField(max_length=20)),
                ('bottle_estimate', models.IntegerField()),
                ('cement_estimate', models.FloatField()),
                ('fill_estimate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='bottle_building',
            name='coordinates',
            field=models.ManyToManyField(related_name='_bottle_building_coordinates_+', to='Bottle_Building.Coordinates'),
        ),
        migrations.AddField(
            model_name='bottle_building',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
