# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-08-21 01:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bottle_Building', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottle_building',
            name='title',
            field=models.CharField(default='', max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bottle_building',
            name='visible_to_members',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bottle_building',
            name='visible_to_public',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bottle_building',
            name='visible_to_those_with_link',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
