# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-12-20 00:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Bottle_Building', '0002_auto_20170821_0125'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bottle_building',
            name='coordinates',
        ),
        migrations.AddField(
            model_name='coordinates',
            name='bottle_building',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Bottle_Building.Bottle_Building'),
        ),
        migrations.AlterField(
            model_name='bottle_building',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
