# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2017-12-24 00:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bottle_Building', '0003_auto_20171220_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='bottle_building',
            name='building_height',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bottle_building',
            name='building_height_units',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
